name: release

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push dev image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: okteto/aspnetcore-getting-started:dev
          target: dev
          context: ./hello-world
      - name: Build and push prod image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: okteto/aspnetcore-getting-started:hello-world
          context: ./hello-world
